---
title: "`r paste0('Submission Batch Review (', params$group, ')')`"
author: "MitoPilot"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    self_contained: true
    highlight: zenburn
params:
  db_path: ""
  group: ""
---

```{r setup, include=FALSE, dev="CairoPNG"}
# force R to use the Cairo package to avoid issues rendering via R studio server
# see https://stackoverflow.com/questions/44731625/rmarkdown-with-no-x11
knitr::opts_chunk$set(echo = TRUE, dev = "CairoPNG")
```

```{r, echo=F, message=T, warning=F}
library(dplyr)
library(msaR)

con <- DBI::dbConnect(RSQLite::SQLite(), dbname = params$db_path)

group <- params$group

annotations <- dplyr::tbl(con, "samples") |>
  dplyr::filter(export_group == !!group) |>
  dplyr::select(ID) |>
  dplyr::left_join(dplyr::tbl(con, "annotations") |>
              dplyr::filter(pos1 > 0 & type == "PCG"),
            by = "ID") |>
  dplyr::collect()

# logic to merge exons if present
IDs <- dplyr::tbl(con, "samples") |>
  dplyr::filter(export_group == !!group) |>
  dplyr::pull("ID")


# Create an empty vector to store the row indices of exons that should be removed after being merged
rows_to_remove <- integer(0)

for (ID in IDs) {
  
  # Get curation rules for the current ID
  curation_opts <- dplyr::tbl(con, "annotate") |>
    dplyr::filter(ID == !!ID) |>
    dplyr::pull("curate_opts")
  
  curate_rules <- dplyr::tbl(con, "curate_opts") |>
    dplyr::filter(curate_opts == !!curation_opts) |>
    dplyr::pull("params") |>
    jsonlite::fromJSON()
  
  # Get sample data
  dat <- dplyr::tbl(con, "samples") |>
    dplyr::select(-dplyr::any_of("topology")) |>
    dplyr::filter(ID == !!ID) |>
    dplyr::left_join(
      dplyr::tbl(con, "annotate") |>
        dplyr::select(ID, topology, path) |>
        dplyr::distinct(),
      by = "ID"
    ) |>
    dplyr::collect()
  
  # Get mitogenome sequence
  seq <- MitoPilot::get_assembly(
    ID = ID,
    path = dat$path,
    con = con
  )
  if (length(seq) > 1) {
    stop("Multiple sequences found. Export not supported for fragmented assemblies.")
  }
  
  # Get all unique genes for the current ID to avoid processing the same gene multiple times
  genes_in_id <- unique(annotations$gene[annotations$ID == ID])
  
  # Loop over each unique gene within the current ID
  for (current_gene in genes_in_id) {
    
    # Find all rows (exons) for this specific gene and ID
    exons_idx <- which(annotations$ID == ID & annotations$gene == current_gene)
    
    # Skip if this gene has already been processed (i.e., its exons were marked for removal)
    if (any(exons_idx %in% rows_to_remove)) next
    
    # Proceed only if there is more than one exon for this gene
    if (length(exons_idx) <= 1) next
    
    cur <- annotations[exons_idx[1], ] # Use the first exon as the reference
    
    # Get curation rules for the gene (intron, start/stop codons)
    cur_rules <- curate_rules$rules[[cur$gene]]
    
    intron <- cur_rules$intron %||% curate_rules$default_rules$PCG$intron %||% FALSE
    
    # If the intron rule is TRUE and we have multiple exons, merge them
    if (intron) {
      exons <- annotations[exons_idx, ]
      exon_seqs <- character(nrow(exons))
      
      message(paste("Merged", length(exon_seqs), "exons for sample", ID, ", gene", cur$gene))

      if (all(exons$direction == "+")) {
        for (i in 1:nrow(exons)) {
          exon_seqs[i] <- as.character(Biostrings::subseq(seq, start = exons$pos1[i], end = exons$pos2[i]))
        }
        merged_sequence <- Biostrings::DNAString(paste(exon_seqs, collapse = ""))
        
      } else if (all(exons$direction == "-")) {
        for (i in 1:nrow(exons)) {
          exon_seqs[i] <- as.character(Biostrings::subseq(seq, start = exons$pos1[i], end = exons$pos2[i]))
        }
        merged_sequence <- Biostrings::DNAString(paste(exon_seqs, collapse = "")) |>
          Biostrings::reverseComplement()
        
      } else {
        message(crayon::red(paste("Warning: exons on opposite strands for gene", cur$gene)))
        next # Skip to the next gene if strands are inconsistent
      }
      
      # Translate the merged sequence
      translation <- Biostrings::translate(
        merged_sequence,
        genetic.code = Biostrings::getGeneticCode(as.character(dat$genetic_code))
      ) |> as.character()
      translation <- sub("\\*$", "", translation) # remove terminal stop codon
      
      # 1. Update the translation for the FIRST exon in the main data frame
      annotations[exons_idx[1], "translation"] <- translation
      
      # 2. Add the indices of the OTHER exons to our list for later removal
      rows_to_remove <- c(rows_to_remove, exons_idx[-1])
    }
  }
}

# After the loop is completely finished, remove all the marked rows in one single step.
if (length(rows_to_remove) > 0) {
  annotations <- annotations[-rows_to_remove, ]
}
```

# PCG Alignments

*****

## NAD1

```{r nad1, echo=F, cache=F}
gene <- "nad1"
gene_seqs <- annotations |>
  dplyr::filter(gene == !!gene) |>
  pull(translation, ID) |>
  Biostrings::AAStringSet()
gene_aln <- DECIPHER::AlignSeqs(
  gene_seqs,
  processors = NULL,
  verbose = FALSE
)
dst <- DECIPHER::DistanceMatrix(gene_aln,
  includeTerminalGaps = T,
  processors = NULL, type = "dist",
  verbose = F
)
clust <- hclust(dst, "complete")
msaR(
  gene_aln[clust$order],
  overviewbox = FALSE,
  seqlogo = FALSE,
  menu = FALSE,
  conservation = TRUE,
  labelNameLength = 150,
  colorscheme = "zappo",
  alignmentHeight = 400
)
```

## NAD2

```{r nad2, echo=F, cache=F}
gene <- "nad2"
gene_seqs <- annotations |>
  dplyr::filter(gene == !!gene) |>
  pull(translation, ID) |>
  Biostrings::AAStringSet()
gene_aln <- DECIPHER::AlignSeqs(
  gene_seqs,
  processors = NULL,
  verbose = FALSE
)
dst <- DECIPHER::DistanceMatrix(gene_aln,
  includeTerminalGaps = T,
  processors = NULL, type = "dist",
  verbose = F
)
clust <- hclust(dst, "complete")
msaR(
  gene_aln[clust$order],
  overviewbox = FALSE,
  seqlogo = FALSE,
  menu = FALSE,
  conservation = TRUE,
  labelNameLength = 150,
  colorscheme = "zappo",
  alignmentHeight = 400
)
```

## COX1

```{r cox1, echo=F, cache=F}
gene <- "cox1"
gene_seqs <- annotations |>
  dplyr::filter(gene == !!gene) |>
  pull(translation, ID) |>
  Biostrings::AAStringSet()
gene_aln <- DECIPHER::AlignSeqs(
  gene_seqs,
  processors = NULL,
  verbose = FALSE
)
dst <- DECIPHER::DistanceMatrix(gene_aln,
  includeTerminalGaps = T,
  processors = NULL, type = "dist",
  verbose = F
)
clust <- hclust(dst, "complete")
msaR(
  gene_aln[clust$order],
  overviewbox = FALSE,
  seqlogo = FALSE,
  menu = FALSE,
  conservation = TRUE,
  labelNameLength = 150,
  colorscheme = "zappo",
  alignmentHeight = 400
)
```

## COX2

```{r cox2, echo=F, cache=F}
gene <- "cox2"
gene_seqs <- annotations |>
  dplyr::filter(gene == !!gene) |>
  pull(translation, ID) |>
  Biostrings::AAStringSet()
gene_aln <- DECIPHER::AlignSeqs(
  gene_seqs,
  processors = NULL,
  verbose = FALSE
)
dst <- DECIPHER::DistanceMatrix(gene_aln,
  includeTerminalGaps = T,
  processors = NULL, type = "dist",
  verbose = F
)
clust <- hclust(dst, "complete")
msaR(
  gene_aln[clust$order],
  overviewbox = FALSE,
  seqlogo = FALSE,
  menu = FALSE,
  conservation = TRUE,
  labelNameLength = 150,
  colorscheme = "zappo",
  alignmentHeight = 400
)
```

## ATP8

```{r atp8, echo=F, cache=F}
gene <- "atp8"
gene_seqs <- annotations |>
  dplyr::filter(gene == !!gene) |>
  pull(translation, ID) |>
  Biostrings::AAStringSet()
gene_aln <- DECIPHER::AlignSeqs(
  gene_seqs,
  processors = NULL,
  verbose = FALSE
)
dst <- DECIPHER::DistanceMatrix(gene_aln,
  includeTerminalGaps = T,
  processors = NULL, type = "dist",
  verbose = F
)
clust <- hclust(dst, "complete")
msaR(
  gene_aln[clust$order],
  overviewbox = FALSE,
  seqlogo = FALSE,
  menu = FALSE,
  conservation = TRUE,
  labelNameLength = 150,
  colorscheme = "zappo",
  alignmentHeight = 400
)
```

## ATP6

```{r atp6, echo=F, cache=F}
gene <- "atp6"
gene_seqs <- annotations |>
  dplyr::filter(gene == !!gene) |>
  pull(translation, ID) |>
  Biostrings::AAStringSet()
gene_aln <- DECIPHER::AlignSeqs(
  gene_seqs,
  processors = NULL,
  verbose = FALSE
)
dst <- DECIPHER::DistanceMatrix(gene_aln,
  includeTerminalGaps = T,
  processors = NULL, type = "dist",
  verbose = F
)
clust <- hclust(dst, "complete")
msaR(
  gene_aln[clust$order],
  overviewbox = FALSE,
  seqlogo = FALSE,
  menu = FALSE,
  conservation = TRUE,
  labelNameLength = 150,
  colorscheme = "zappo",
  alignmentHeight = 400
)
```

## COX3

```{r cox3, echo=F, cache=F}
gene <- "cox3"
gene_seqs <- annotations |>
  dplyr::filter(gene == !!gene) |>
  pull(translation, ID) |>
  Biostrings::AAStringSet()
gene_aln <- DECIPHER::AlignSeqs(
  gene_seqs,
  processors = NULL,
  verbose = FALSE
)
dst <- DECIPHER::DistanceMatrix(gene_aln,
  includeTerminalGaps = T,
  processors = NULL, type = "dist",
  verbose = F
)
clust <- hclust(dst, "complete")
msaR(
  gene_aln[clust$order],
  overviewbox = FALSE,
  seqlogo = FALSE,
  menu = FALSE,
  conservation = TRUE,
  labelNameLength = 150,
  colorscheme = "zappo",
  alignmentHeight = 400
)
```

## NAD3

```{r nad3, echo=F, cache=F}
gene <- "nad3"
gene_seqs <- annotations |>
  dplyr::filter(gene == !!gene) |>
  pull(translation, ID) |>
  Biostrings::AAStringSet()
gene_aln <- DECIPHER::AlignSeqs(
  gene_seqs,
  processors = NULL,
  verbose = FALSE
)
dst <- DECIPHER::DistanceMatrix(gene_aln,
  includeTerminalGaps = T,
  processors = NULL, type = "dist",
  verbose = F
)
clust <- hclust(dst, "complete")
msaR(
  gene_aln[clust$order],
  overviewbox = FALSE,
  seqlogo = FALSE,
  menu = FALSE,
  conservation = TRUE,
  labelNameLength = 150,
  colorscheme = "zappo",
  alignmentHeight = 400
)
```

## NAD4

```{r nad4, echo=F, cache=F}
gene <- "nad4"
gene_seqs <- annotations |>
  dplyr::filter(gene == !!gene) |>
  pull(translation, ID) |>
  Biostrings::AAStringSet()
gene_aln <- DECIPHER::AlignSeqs(
  gene_seqs,
  processors = NULL,
  verbose = FALSE
)
dst <- DECIPHER::DistanceMatrix(gene_aln,
  includeTerminalGaps = T,
  processors = NULL, type = "dist",
  verbose = F
)
clust <- hclust(dst, "complete")
msaR(
  gene_aln[clust$order],
  overviewbox = FALSE,
  seqlogo = FALSE,
  menu = FALSE,
  conservation = TRUE,
  labelNameLength = 150,
  colorscheme = "zappo",
  alignmentHeight = 400
)
```

## NAD4l

```{r nad4l, echo=F, cache=F}
gene <- "nad4l"
gene_seqs <- annotations |>
  dplyr::filter(gene == !!gene) |>
  pull(translation, ID) |>
  Biostrings::AAStringSet()
gene_aln <- DECIPHER::AlignSeqs(
  gene_seqs,
  processors = NULL,
  verbose = FALSE
)
dst <- DECIPHER::DistanceMatrix(gene_aln,
  includeTerminalGaps = T,
  processors = NULL, type = "dist",
  verbose = F
)
clust <- hclust(dst, "complete")
msaR(
  gene_aln[clust$order],
  overviewbox = FALSE,
  seqlogo = FALSE,
  menu = FALSE,
  conservation = TRUE,
  labelNameLength = 150,
  colorscheme = "zappo",
  alignmentHeight = 400
)
```

## NAD5

```{r nad5, echo=F, cache=F}
gene <- "nad5"
gene_seqs <- annotations |>
  dplyr::filter(gene == !!gene) |>
  pull(translation, ID) |>
  Biostrings::AAStringSet()
gene_aln <- DECIPHER::AlignSeqs(
  gene_seqs,
  processors = NULL,
  verbose = FALSE
)
dst <- DECIPHER::DistanceMatrix(gene_aln,
  includeTerminalGaps = T,
  processors = NULL, type = "dist",
  verbose = F
)
clust <- hclust(dst, "complete")
msaR(
  gene_aln[clust$order],
  overviewbox = FALSE,
  seqlogo = FALSE,
  menu = FALSE,
  conservation = TRUE,
  labelNameLength = 150,
  colorscheme = "zappo",
  alignmentHeight = 400
)
```

## NAD6

```{r nad6, echo=F, cache=F}
gene <- "nad6"
gene_seqs <- annotations |>
  dplyr::filter(gene == !!gene) |>
  pull(translation, ID) |>
  Biostrings::AAStringSet()
gene_aln <- DECIPHER::AlignSeqs(
  gene_seqs,
  processors = NULL,
  verbose = FALSE
)
dst <- DECIPHER::DistanceMatrix(gene_aln,
  includeTerminalGaps = T,
  processors = NULL, type = "dist",
  verbose = F
)
clust <- hclust(dst, "complete")
msaR(
  gene_aln[clust$order],
  overviewbox = FALSE,
  seqlogo = FALSE,
  menu = FALSE,
  conservation = TRUE,
  labelNameLength = 150,
  colorscheme = "zappo",
  alignmentHeight = 400
)
```

## CYTB

```{r cob, echo=F, cache=F}
gene <- "cob"
gene_seqs <- annotations |>
  dplyr::filter(gene == !!gene) |>
  pull(translation, ID) |>
  Biostrings::AAStringSet()
gene_aln <- DECIPHER::AlignSeqs(
  gene_seqs,
  processors = NULL,
  verbose = FALSE
)
dst <- DECIPHER::DistanceMatrix(gene_aln,
  includeTerminalGaps = T,
  processors = NULL, type = "dist",
  verbose = F
)
clust <- hclust(dst, "complete")
msaR(
  gene_aln[clust$order],
  overviewbox = FALSE,
  seqlogo = FALSE,
  menu = FALSE,
  conservation = TRUE,
  labelNameLength = 150,
  colorscheme = "zappo",
  alignmentHeight = 400
)
```
