#' Convert a GenBank 5-column feature table to GFF3 format.
#'
#' DEPRECATED and unmaintained: not used by MitoPilot's pipeline or app, and
#' retained only for potential future use. It has known bugs and is not exported.
#'
#' Function to take a GenBank feature table generated by MitoPilot and
#' convert it to GFF3 format, one GFF file per sample.
#' Could be useful for generating GFF files to review in Geneious
#' after manually editing the feature table in a text editor.
#'
#' NOTE: this function has only been tested with GenBank feature tables produced by MitoPilot.
#' It likely will not work for a feature table downloaded directly from GenBank.
#'
#' @param tbl Full path to GenBank feature table
#' @param assembly_lengths Two column tab-delimited file with no headers, first column sample ID (must match IDs in feature table), second column mitogenome length (in bp)
#' @param out Output directory for GFF files, will be created if it does not exist
#'
#' @keywords internal
#' @noRd
tbl_to_gff3 <- function(tbl = NULL,
                        assembly_lengths = NULL,
                        out = NULL) {
  .Deprecated(msg = "tbl_to_gff3() is deprecated and unmaintained.")

  # check feature table exists
  if (!file.exists(tbl)) {
    # if not stop and print an error message
    stop(paste("Error: Feature table not found at path:", filepath))
  }

  # check assembly_lengths table exists
  if (!file.exists(assembly_lengths)) {
    # if not stop and print an error message
    stop(paste("Error: Table of assembly lengths not found at path:", filepath))
  }

  # check if out directory exists
  if (dir.exists(out)) {
    # if out dir exists, stop
    stop(
      paste0(
        "Error: Output directory already exists, aborting to prevent potential overwrites"
      )
    )
  } else {
    # if out dir doesn't exist, create it
    dir.create(out, recursive = TRUE)
  }

  # read table file into memory
  tbl_lines <- readLines(tbl)

  # read asmb lens into memory
  asmb_lens <- read.table(assembly_lengths)

  # loop through table file line by line
  # and write to GFF files
  for (i in 1:length(tbl_lines)) {
    line = tbl_lines[i]
    if (startsWith(line, ">Feature")) {
      sample <- gsub(">Feature ", "", line, fixed = TRUE)
      sample_asmb_len <- asmb_lens[which(asmb_lens[, 1] == sample), 2]
      writeLines(text = c(
        "##gff-version 3",
        paste0(
          sample,
          "\tMitoPilot\tregion\t1\t",
          sample_asmb_len,
          "\t.\t+\t.\tID=",
          sample,
          ":1..",
          sample_asmb_len,
          ";Name=MT;mol_type=genomic DNA"
        )
      ),
      con = file.path(out, paste0(sample, ".gff")))
    } else if (endsWith(line, "gene")) {
      line_split <- strsplit(line, "\t")
      gene <- strsplit(tbl_lines[i + 1], "\t")[[1]][5]
      if (as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])) < as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))) {
        dir <- "+"
      } else {
        dir <- "-"
      }
      # get gene type
      gene_type <- strsplit(tbl_lines[i + 2], "\t")[[1]][3]
      # write to GFF
      if (gene_type == "CDS") {
        write(
          paste0(
            sample,
            "\tMitoPilot\tgene\t",
            min(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            "\t",
            max(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            "\t.\t",
            dir,
            "\t.\tID=gene-",
            gene,
            ";Name=",
            gene,
            ";gbkey=Gene;gene=",
            gene,
            ";gene_biotype=protein_coding"
          ),
          file = file.path(out, paste0(sample, ".gff")),
          append = TRUE
        )
        for (j in i + 2:length(tbl_lines)) {
          if (grepl("product", tbl_lines[j])) {
            # if line contains the word product, we have reached the end of the CDSs for this gene
            # now we can get the product name and translation table
            product <- strsplit(tbl_lines[j], "\t")[[1]][5]
            transl_table <- strsplit(tbl_lines[j + 1], "\t")[[1]][5]
            break
          }
        }
        # if only one CDS (one exon)
        if ( grepl("product", tbl_lines[i + 3]) ) {
          line_split <- strsplit(tbl_lines[i + 2], "\t")
          write(
            paste0(
              sample,
              "\tMitoPilot\tCDS\t",
              min(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
              "\t",
              max(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
              "\t.\t",
              dir,
              "\t.\tID=cds-",
              gene,
              ";Parent=gene-",
              sample,
              ";Name=",
              gene,
              ";gbkey=CDS;gene=",
              gene,
              ";product=",
              product,
              ";transl_table=",
              transl_table
            ),
            file = file.path(out, paste0(sample, ".gff")),
            append = TRUE
          )
        } else {
          # gene has multiple CDSs (exons)
          for (j in (i + 2):length(tbl_lines)) {
            if (grepl("product", tbl_lines[j])) {
              # if line contains the word product, we have reached the end of the CDSs for this gene
              break
            } else {
              line_split <- strsplit(tbl_lines[j], "\t")
              write(
                paste0(
                  sample,
                  "\tMitoPilot\tCDS\t",
                  min(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
                  "\t",
                  max(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
                  "\t.\t",
                  dir,
                  "\t.\tID=cds-",
                  gene,
                  ";Parent=gene-",
                  sample,
                  ";Name=",
                  gene,
                  ";gbkey=CDS;gene=",
                  gene,
                  ";product=",
                  product,
                  ";transl_table=",
                  transl_table
                ),
                file = file.path(out, paste0(sample, ".gff")),
                append = TRUE
              )
            }
          }

        }
      } else if (gene_type == "tRNA") {
        product <- strsplit(tbl_lines[i + 3], "\t")[[1]][5]
        write(
          paste0(
            sample,
            "\tMitoPilot\ttRNA\t",
            min(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            "\t",
            max(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            "\t.\t",
            dir,
            "\t.\tID=rna-",
            sample,
            ":",
            min(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            "..",
            max(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            ";Name=",
            gene,
            ";gbkey=tRNA;product=",
            product
          ),
          file = file.path(out, paste0(sample, ".gff")),
          append = TRUE
        )
        write(
          paste0(
            sample,
            "\tMitoPilot\texon\t",
            min(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            "\t",
            max(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            "\t.\t",
            dir,
            "\t.\tID=exon-",
            sample,
            ":",
            min(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            "..",
            max(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            ";Parent=rna-",
            sample,
            ":",
            min(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            "..",
            max(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            ";gbkey=tRNA;product=",
            product
          ),
          file = file.path(out, paste0(sample, ".gff")),
          append = TRUE
        )
      } else if (gene_type == "rRNA") {
        product <- strsplit(tbl_lines[i + 3], "\t")[[1]][5]
        gene <- ifelse(gene == "l-rRNA", "rrnL", "rrnS") # change format of rRNA name
        write(
          paste0(
            sample,
            "\tMitoPilot\trRNA\t",
            min(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            "\t",
            max(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            "\t.\t",
            dir,
            "\t.\tID=rna-",
            sample,
            ":",
            min(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            "..",
            max(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            ";Name=",
            gene,
            ";gbkey=rRNA;product=",
            product
          ),
          file = file.path(out, paste0(sample, ".gff")),
          append = TRUE
        )
        write(
          paste0(
            sample,
            "\tMitoPilot\texon\t",
            min(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            "\t",
            max(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            "\t.\t",
            dir,
            "\t.\tID=exon-",
            sample,
            ":",
            min(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            "..",
            max(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            ";Parent=rna-",
            sample,
            ":",
            min(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            "..",
            max(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
            ";gbkey=rRNA;product=",
            product
          ),
          file = file.path(out, paste0(sample, ".gff")),
          append = TRUE
        )
      } else {
        message(
          paste0(
            "Error: No valid gene type found for gene on line ",
            i,
            " of the feature table"
          )
        )
        stop("Must be protein-coding, tRNA, or rRNA")
      }
    } else if(endsWith(line, "D-loop")){
      line_split <- strsplit(line, "\t")
      if (as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])) < as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))) {
        dir <- "+"
      } else {
        dir <- "-"
      }
      write(
        paste0(
          sample,
          "\tMitoPilot\tD_loop\t",
          min(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
          "\t",
          max(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
          "\t.\t",
          dir,
          "\t.\tID=ctrl-",
          sample,
          ":",
          min(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
          "..",
          max(as.numeric(gsub("[^0-9.-]", "", line_split[[1]][1])), as.numeric(gsub("[^0-9.-]", "", line_split[[1]][2]))),
          ";gbkey=D-loop;Note=control region"
        ),
        file = file.path(out, paste0(sample, ".gff")),
        append = TRUE
      )
    }
  }
}
